FRAME_WIDTH = 800
FRAME_HEIGHT = 730

FHD_W = 1920
FHD_H = 1080

LOGIN_WINDOW_WIDTH = 600
LOGIN_WINDOW_HEIGHT = 125

WINDOW_TITLE = 'Distributed Versioning System Python Client'

ADD_AUTHORIZED_WIDTH = 430
ADD_AUTHORIZED_HEIGHT = 200

NUMBER_OF_DISPLAYED_TRANSACTIONS = 5
